#!/usr/bin/env bash
# Optional search arm: re-search one spike-in mixture with Sage and
# compare it with the Proteome Discoverer export on that mixture.
#
# Off by default and not run for the results in this repository. It is
# here to keep the search engine question alive for stage 5 of the
# roadmap, which will reprocess TMT from RAW at scale. Nothing in the
# core results depends on it.
#
# What it does when run:
#   1. Disk gate: fetch the first RAW file of the chosen mixture from
#      MassIVE MSV000084266 (the MS2 acquisition, so Sage can quantify at
#      MS level 2), measure it, project the total for three RAW files,
#      their gzipped mzML conversions and the search outputs, and refuse
#      to continue if that exceeds DISK_GB from project.conf minus a
#      2 GB margin.
#   2. Fetch the remaining RAW files and convert with ThermoRawFileParser
#      to gzipped mzML, with the same options as the label-free repository.
#   3. Build the search database: the UniProt human reference proteome
#      (UP000005640, one sequence per gene) plus the Sigma UPS1 sequences
#      that the original submission deposited under sequence/ in the
#      MassIVE container. Source URLs and download dates are written to
#      results/sage/database_provenance.tsv.
#   4. Search with Sage using config/sage_spikein_ms2.json. TMT reporter
#      extraction is configured through quant.tmt = Tmt10 with
#      tmt_settings.level = 2 (this is MS2 data). The quant block only
#      controls reporter extraction: the TMT10 label mass 229.162932 has
#      to be declared as a static modification on K and on the peptide
#      N-terminus in database.static_mods, which the config does. sn
#      stays false because ThermoRawFileParser does not write noise
#      arrays unless asked and Sage needs them for signal to noise.
#      Decoys are generated by Sage internally (generate_decoys = true).
#   5. Compare with the PD table for the same three runs
#      (scripts/lib/compare_search_arm.R): PSM counts at 1 per cent
#      FDR, identification overlap by peptide sequence, per-channel
#      reporter correlation on shared PSMs, and differential abundance
#      calls from the same protein-level mixed model.
#
# Requirements on PATH: sage, ThermoRawFileParser (or mono plus the
# ThermoRawFileParser.exe path in THERMORAWFILEPARSER), curl.
#
# Usage: scripts/10_search_arm.sh [--mixture N] [--force]

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=/dev/null
source "$ROOT/project.conf"
STAMP="$ROOT/logs/10_search_arm.done"
MIXTURE=1
FORCE=0
for arg in "$@"; do
    case "$arg" in
        --mixture) shift; MIXTURE="$1" ;;
        --force) FORCE=1 ;;
        --help|-h) sed -n '2,45p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    esac
done

if [[ -f "$STAMP" && $FORCE -eq 0 ]]; then
    echo "10_search_arm: already completed on $(cat "$STAMP"); skipping (use --force to redo)."
    exit 0
fi

OUT="$ROOT/results/sage"
RAWDIR="$ROOT/data/search_arm"
mkdir -p "$OUT" "$RAWDIR" "$ROOT/logs"
START=$(date +%s)

need() { command -v "$1" >/dev/null 2>&1 || { echo "10_search_arm: $1 not found on PATH; install it or skip the arm" >&2; exit 3; }; }
need curl
need sage
if [[ -z "${THERMORAWFILEPARSER:-}" ]]; then
    if command -v ThermoRawFileParser >/dev/null 2>&1; then THERMORAWFILEPARSER="ThermoRawFileParser"
    elif command -v thermorawfileparser >/dev/null 2>&1; then THERMORAWFILEPARSER="thermorawfileparser"
    else echo "10_search_arm: ThermoRawFileParser not found; set THERMORAWFILEPARSER" >&2; exit 3; fi
fi

MSV="MSV000084266"
RAWS=()
for rep in 01 02 03; do
    RAWS+=("161122_SILAC_HeLa_UPS1_TMT10_MS2_Mixture${MIXTURE}_${rep}.raw")
done
massive_url() { printf 'https://massive.ucsd.edu/ProteoSAFe/DownloadResultFile?file=f.%s/raw/RawFiles/%s&forceDownload=true' "$MSV" "$1"; }

# ---- 1. Disk gate on the first RAW file --------------------------------------
first="${RAWS[0]}"
if [[ ! -s "$RAWDIR/$first" ]]; then
    echo "10_search_arm: fetching $first to measure it"
    curl -L --fail --retry 3 -o "$RAWDIR/$first" "$(massive_url "$first")"
fi
RAW_BYTES=$(stat -c %s "$RAWDIR/$first" 2>/dev/null || stat -f %z "$RAWDIR/$first")
# Three RAW files, gzipped mzML at roughly 0.6 of RAW, Sage output and
# working space at roughly 0.3 of RAW: 1.9 times the RAW total.
PROJECTED_GB=$(( RAW_BYTES * 3 * 19 / 10 / 1024 / 1024 / 1024 + 1 ))
FREE_GB=$(df -Pk "$ROOT" | awk 'NR==2 {printf "%d", $4/1024/1024}')
echo "10_search_arm: first RAW is $(( RAW_BYTES / 1024 / 1024 )) MB; projected need ${PROJECTED_GB} GB; free ${FREE_GB} GB; budget ${DISK_GB} GB"
if [[ $PROJECTED_GB -gt $(( DISK_GB - 2 )) || $PROJECTED_GB -gt $(( FREE_GB - 2 )) ]]; then
    echo "10_search_arm: refusing to start; projected ${PROJECTED_GB} GB does not fit" >&2
    printf "stage\telapsed_s\tpeak_rss_mb\tnote\n10_search_arm\t%d\tNA\trefused: projected %d GB, free %d GB\n" \
        "$(( $(date +%s) - START ))" "$PROJECTED_GB" "$FREE_GB" > "$ROOT/logs/10_search_arm.resources.tsv"
    exit 4
fi

# ---- 2. Remaining RAW files and conversion -------------------------------------
for f in "${RAWS[@]}"; do
    if [[ ! -s "$RAWDIR/$f" ]]; then
        echo "10_search_arm: fetching $f"
        curl -L --fail --retry 3 -o "$RAWDIR/$f" "$(massive_url "$f")"
    fi
    mz="$RAWDIR/${f%.raw}.mzML.gz"
    if [[ ! -s "$mz" ]]; then
        echo "10_search_arm: converting $f"
        # -f 2: indexed mzML; -g: gzip. Vendor peak picking stays on
        # (no -p): Sage needs centroided spectra.
        "$THERMORAWFILEPARSER" -i "$RAWDIR/$f" -o "$RAWDIR" -f 2 -g
    fi
done

# ---- 3. Search database ---------------------------------------------------------
FASTA="$RAWDIR/human_ups1.fasta"
if [[ ! -s "$FASTA" ]]; then
    echo "10_search_arm: building search database"
    curl -L --fail --retry 3 -o "$RAWDIR/human_reference_proteome.fasta.gz" \
        "https://rest.uniprot.org/uniprotkb/stream?compressed=true&format=fasta&query=(proteome:UP000005640)"
    curl -L --fail --retry 3 -o "$RAWDIR/Sigma_UPS.fasta" \
        "https://massive.ucsd.edu/ProteoSAFe/DownloadResultFile?file=f.${MSV}/sequence/Sigma_UPS.fasta&forceDownload=true"
    gzip -dc "$RAWDIR/human_reference_proteome.fasta.gz" > "$FASTA"
    cat "$RAWDIR/Sigma_UPS.fasta" >> "$FASTA"
    {
        printf "component\tsource\tretrieved\tsha256\n"
        printf "human reference proteome UP000005640\thttps://rest.uniprot.org/uniprotkb/stream?query=(proteome:UP000005640)\t%s\t%s\n" \
            "$(date -u +%Y-%m-%d)" "$(sha256sum "$RAWDIR/human_reference_proteome.fasta.gz" | cut -d' ' -f1)"
        printf "Sigma UPS1 sequences\tMassIVE %s sequence/Sigma_UPS.fasta\t%s\t%s\n" \
            "$MSV" "$(date -u +%Y-%m-%d)" "$(sha256sum "$RAWDIR/Sigma_UPS.fasta" | cut -d' ' -f1)"
    } > "$OUT/database_provenance.tsv"
fi

# ---- 4. Sage -------------------------------------------------------------------
if [[ ! -s "$OUT/results.sage.tsv" ]]; then
    echo "10_search_arm: running sage $(sage --version 2>&1 | head -1)"
    ( cd "$ROOT" && sage --batch-size 1 -o "$OUT" "$ROOT/config/sage_spikein_ms2.json" "$RAWDIR"/*.mzML.gz )
    sage --version > "$OUT/sage_version.txt" 2>&1 || true
fi

# ---- 5. Comparison --------------------------------------------------------------
"$RSCRIPT" "$ROOT/scripts/lib/compare_search_arm.R" --mixture "$MIXTURE"

END=$(date +%s)
printf "stage\telapsed_s\tpeak_rss_mb\tnote\n10_search_arm\t%d\tNA\tmixture=%d\n" "$((END-START))" "$MIXTURE" > "$ROOT/logs/10_search_arm.resources.tsv"
date -u +%Y-%m-%dT%H:%M:%SZ > "$STAMP"
echo "10_search_arm: done in $((END-START)) s"
